-- Fix trades table - add missing columns
ALTER TABLE trades ADD COLUMN IF NOT EXISTS entry_time TIMESTAMP;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS exit_time TIMESTAMP;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS pnl DECIMAL(10,2);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS emotion VARCHAR(50);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS setup VARCHAR(100);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS execution_quality VARCHAR(10);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS duration VARCHAR(50);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS checklist_id INTEGER REFERENCES checklists(id) ON DELETE SET NULL;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS checklist_completed JSONB;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS screenshot VARCHAR(500);

-- Verify the changes
\d trades 