// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urciudgceezbggqxspap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyY2l1ZGdjZWV6YmdncXhzcGFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzQ2NzYsImV4cCI6MjA1ODUxMDY3Nn0.Jmk8nVegzCDrvbx9r-GuyfQoqiWizkyfuGBKvaekhG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);